### ISSUE TITLE
2 featured content cards type incorrect weight and size

### ISSUE THREAD

**Issue by caitlynmayers** [tfuqua/ukrops_homemades#10]
### Location

http://homemades.taylorfuqua.com/
### Description

The font weights, sizes and heading text transform are incorrect per the comp.
### Screenshot

<img width="1250" alt="screen shot 2016-10-19 at 11 14 01 am" src="https://cloud.githubusercontent.com/assets/1574420/19526294/f9b7c6b8-95f1-11e6-926a-e446fc276f02.png">

**Comment by tfuqua** [comment]
Fixed this by changing to 

`text-transform:capitalize;`

was inheriting the styles from parent theme

**Comment by caitlynmayers** [comment]
Fix verified.

**Comment by caitlynmayers** [comment]
Fix verified.
