### ISSUE TITLE
Type weights & sizes incorrect

### ISSUE THREAD

**Issue by caitlynmayers** [tfuqua/ukrops_homemades#13]
### Location

http://homemades.taylorfuqua.com/
### Description

The From Our Kitchen block's type is the incorrect weights and sizes per the comp.
### Screenshot

<img width="517" alt="screen shot 2016-10-19 at 11 14 12 am" src="https://cloud.githubusercontent.com/assets/1574420/19526532/b12d90f2-95f2-11e6-98ae-5b00058c239a.png">

**Comment by tfuqua** [comment]
Font specs should match zeplin specs

`
font-size: 22px;
font-weight: 400;
font-style: normal;
font-stretch: normal;
line-height: 1.59;
color: #794400;
`

**Comment by caitlynmayers** [comment]
Fix verified.
