### ISSUE TITLE
Swap image placement on responsive breakdown

### ISSUE THREAD

**Issue by caitlynmayers** [tfuqua/ukrops_homemades#14]
### Location

http://homemades.taylorfuqua.com/
### Description

Swap the image placement at 320 so the chicken pot pie is beneath the text. This should be done in this block consistently throughout the site.
### Screenshot

<img width="345" alt="screen shot 2016-10-19 at 11 59 08 am" src="https://cloud.githubusercontent.com/assets/1574420/19526797/983240a6-95f3-11e6-9e11-2b80fbdd8a61.png">

**Comment by tfuqua** [comment]
@caitlynmayers I"m thinking this issue might not be an issue after adding the new image supplied by @agentdoublel. she also had me add opacity to text on smaller devices. Thoughts?

**Comment by caitlynmayers** [comment]
@tfuqua we discussed it yesterday and aren't big fans of adding the white background. We would prefer to see the image stack on top of the text, and that will require a non-cropped asset in order for the bottom edge to not be cut off. To maintain the placement and crop of the image on desktop, you will probably have to change how you implement that image because we would still like to see it cropped there, and I'm not sure how you feel would be best to approach this. The first thing that comes to my mind is using the image as a background image for that image block and setting it to cover, but that probably isn't the right solution, it's just what came to mind first. You can have fun with this!

**Comment by tfuqua** [comment]
B/c the way the plate is cropped at the top and bottom it looks strange by itself as content, so I'll continue to use the Hero Text to help hide some of that. Also added white background to the hero text per LL's request

**Comment by agentdoublel** [comment]
Can you align the white box with the edge of the featured card above it?

<img width="147" alt="screen shot 2016-11-17 at 11 22 35 am" src="https://cloud.githubusercontent.com/assets/17103891/20397561/2c439c4c-acb8-11e6-8f29-f360d36f9a59.png">

**Comment by tfuqua** [comment]
updated alignment of bottom hero text

**Comment by caitlynmayers** [comment]
Fix verified.
