### ISSUE TITLE
Confirm opacity level of all title blocks

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/ukrops_homemades#15]
### Location

Title blocks (in hero area)
### Description

Need to make sure that the opacity level of the white boxes is the same thoughout the sites. (The on on the products page looks closest, but may need to be adjusted. Product detail looks too light.)
### Screenshot

<img width="857" alt="screen shot 2016-10-26 at 10 29 58 am" src="https://cloud.githubusercontent.com/assets/17103891/19730160/4a58b486-9b67-11e6-89de-a539662be634.png">
<img width="810" alt="screen shot 2016-10-26 at 10 31 13 am" src="https://cloud.githubusercontent.com/assets/17103891/19730175/58f5d96a-9b67-11e6-8983-a3c0e30f389e.png">

**Comment by tfuqua** [comment]
Product details had incorrect opacity. fixed.
