### ISSUE TITLE
Footer content

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/ukrops_homemades#18]
### Location

Footer
### Description

Links in footer should always be the links on the comp (Ukrops HSF links). We don't want the footer to have links that are contextual.
### Screenshot

<img width="722" alt="screen shot 2016-10-26 at 10 57 44 am" src="https://cloud.githubusercontent.com/assets/17103891/19731327/10c7cd3e-9b6b-11e6-9db1-2853d2e11ae8.png">

**Comment by agentdoublel** [comment]
It doesnt seem like there's equal spacing between the columns of links. Can we tweak this?

**Comment by tfuqua** [comment]
Updated columns and font-sizing to keep links from going onto two lines
