### ISSUE TITLE
Products - Subcategory - hero image size

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/ukrops_homemades#19]
### Location

Subcategory page (cakes) hero image
### Description

Hero image size looks too tall. Match the size of the comps.
### Screenshot

<img width="722" alt="screen shot 2016-10-26 at 11 03 25 am" src="https://cloud.githubusercontent.com/assets/17103891/19731572/d7fccab2-9b6b-11e6-99dc-f4e6477118d7.png">

**Comment by agentdoublel** [comment]
Looks like it's the right size, but can we center that white box vertically?

**Comment by agentdoublel** [comment]
Center the box or I'll cut ya.

**Comment by tfuqua** [comment]
Fixed to include the mini hero markup. This should fix the alignment of the hero text as well
