### ISSUE TITLE
Products - Subcategory - card text and button styling

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/ukrops_homemades#20]
### Location

Products - Subcategory - Cards
### Description
- Cards copy should display 5 lines of text
- The "order" and "about" text looks bold. Should be Medium. If it already is Medium, then let's take it down to Regular.
### Screenshot

<img width="340" alt="screen shot 2016-10-26 at 11 15 52 am" src="https://cloud.githubusercontent.com/assets/17103891/19732077/9497638e-9b6d-11e6-9e05-fb9715ae5625.png">

**Comment by tfuqua** [comment]
reduced font weight to 400

**Comment by tfuqua** [comment]
Changed excerpt length from 22 to 28 words for homemades to push onto another line

**Comment by agentdoublel** [comment]
I can't see where the breaking onto another line happens, but I trust you that it works.

**Comment by tfuqua** [comment]
I think this issue can be closed. One thing to check LL is that in the scenario of only one button it doesn't have sharp edges and it spans the full width. You can check an example of this here: http://homemades.taylorfuqua.com/product/cakes/

**Comment by agentdoublel** [comment]
That button looks perfect! Good work :)
