### ISSUE TITLE
Products - Subcategories - Card Button Responsiveness 

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/ukrops_homemades#21]
### Location

Products - Subcategories - Cards at tablet (?) screen size
### Description

The buttons text at tablet size is probably too big and starts to get cut off. Let's scale the text down so that it fits. 
### Screenshot

<img width="863" alt="screen shot 2016-10-26 at 11 24 34 am" src="https://cloud.githubusercontent.com/assets/17103891/19732451/ca77cc04-9b6e-11e6-9e2f-0bcf39a9eba4.png">

**Comment by tfuqua** [comment]
changed from 24px to 20px on medium devices
