### ISSUE TITLE
Products - Subcategories - Card button size in mobile

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/ukrops_homemades#22]
### Location

Products - Subcategories - Card button size in mobile
### Description

Buttons become stacked instead of staying a split button. Can we keep the split button?
### Screenshot

<img width="377" alt="screen shot 2016-10-26 at 11 26 14 am" src="https://cloud.githubusercontent.com/assets/17103891/19732543/0618526a-9b6f-11e6-8552-7df2a774ca2d.png">

**Comment by tfuqua** [comment]
After talking with @agentdoublel the buttons are stacked vertially on smaller screen to make sure the content fits ok.
