### ISSUE TITLE
Products - Details Hero image

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/ukrops_homemades#23]
### Location

Hero area
### Description

Also too tall and I need to give you a better image. 
### Screenshot

<img width="722" alt="screen shot 2016-10-26 at 11 33 51 am" src="https://cloud.githubusercontent.com/assets/17103891/19732828/17e70724-9b70-11e6-8a86-08efd69d1f8d.png">

**Comment by tfuqua** [comment]
Updated the markup to display the smaller version of the hero images
