### ISSUE TITLE
Products - Details - body content size

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/ukrops_homemades#24]
### Location

Text content area
### Description

The width of the body text content shouldn't exceed 8 bootstrap columns. If it's already that width, then let's come up with another solution. 

The quote text width, however, should still be 8 columns.
### Screenshot

<img width="1247" alt="screen shot 2016-10-26 at 11 37 47 am" src="https://cloud.githubusercontent.com/assets/17103891/19733046/ccba6ce0-9b70-11e6-8d4c-42cf4b5a00ac.png">

**Comment by tfuqua** [comment]
Changed to 8 columns on large devices. 10 columns on medium devices

**Comment by agentdoublel** [comment]
Looks good, but I messed up and ment to say that the quote area should be wider than the body text. If body is 8. the quote should be 10. My b!

Also, can we increase the line spacing of the body text a bit?

**Comment by tfuqua** [comment]
Updated the blockquote style rules to extend to the full column width on medium and large devices

**Comment by agentdoublel** [comment]
perrrfff
