### ISSUE TITLE
Products - Details - quote carousel styles

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/ukrops_homemades#25]
### Location

Quote/testimonial carosel
### Description
- I'd like to change the quotation marks to Times New Roman. It it's weird to have multiple text styles, then we can make them images or whatever.
- And there needs to be more padding between the bottom of the quote and the beginning of the person who said it (see comp)
### Screenshot

<img width="340" alt="screen shot 2016-10-26 at 11 42 38 am" src="https://cloud.githubusercontent.com/assets/17103891/19733224/58023a9e-9b71-11e6-8711-83d258a2fc36.png">
<img width="343" alt="screen shot 2016-10-26 at 11 42 45 am" src="https://cloud.githubusercontent.com/assets/17103891/19733223/5801692a-9b71-11e6-9351-326d416911a9.png">

**Comment by tfuqua** [comment]
I've added padding between the quote and source. The quote marks are already using:

`font-family: Times New Roman",Times,serif`

**Comment by caitlynmayers** [comment]
Fix verified.
