### ISSUE TITLE
Products - Details Mobile text sizes

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/ukrops_homemades#27]
### Location

Text though out page
### Description

Both the top quote and bottom quote text are too large on tablet and mobile. We should scale this down. We can work together to tweek the sizes. 
### Screenshot

<img width="380" alt="screen shot 2016-10-26 at 2 30 58 pm" src="https://cloud.githubusercontent.com/assets/17103891/19739432/de76a0b2-9b88-11e6-9521-411a7b6fe040.png">
<img width="397" alt="screen shot 2016-10-26 at 2 30 52 pm" src="https://cloud.githubusercontent.com/assets/17103891/19739434/e0eb3b78-9b88-11e6-9f60-e98ce03dd18e.png">

**Comment by tfuqua** [comment]
Updated css to shrink blockquote and quote carousel font sizes on smaller devices

**Comment by agentdoublel** [comment]
The top quote seems to have too much padding on top. Cut it to half that size.
<img width="400" alt="screen shot 2016-11-17 at 12 00 49 pm" src="https://cloud.githubusercontent.com/assets/17103891/20399054/9190fed2-acbd-11e6-9320-d45355cf37b4.png">

The bottom quote needs more padding under the person's name. Specifically in mobile. 
<img width="395" alt="screen shot 2016-11-17 at 12 00 44 pm" src="https://cloud.githubusercontent.com/assets/17103891/20399061/959a0456-acbd-11e6-8e7e-d908b5e0fb2a.png">

**Comment by tfuqua** [comment]
Added 10px on top of source name, and 20px padding on bottom before quote navigation
