### ISSUE TITLE
Products - Details- Mobile quote text sizes

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/ukrops_homemades#28]
### Location

Quote areas (beginning of content and carousel)
### Description

Let's scale down the size of the text in mobile and tablet
### Screenshot

<img width="397" alt="screen shot 2016-10-28 at 11 23 06 am" src="https://cloud.githubusercontent.com/assets/17103891/19811918/8424c470-9d01-11e6-98cd-ac2d26a89436.png">
<img width="395" alt="screen shot 2016-10-28 at 11 23 10 am" src="https://cloud.githubusercontent.com/assets/17103891/19811923/864e33d0-9d01-11e6-9427-1508dda0f3c1.png">

**Comment by tfuqua** [comment]
I think this is a duplicate like #27
