### ISSUE TITLE
Store Locator hero area resize

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/ukrops_homemades#29]
### Location
Store locator page, Hero area

### Description
The hero area for Store locator looks too tall. It should be the same height as the rest of the hero areas on the other pages.

### Screenshot
<img width="1438" alt="screen shot 2016-11-28 at 12 50 49 pm" src="https://cloud.githubusercontent.com/assets/17103891/20679589/90bf6e76-b569-11e6-8e82-59b49f649dff.png">

**Comment by agentdoublel** [comment]
Doesnt look any different to me.

**Comment by tfuqua** [comment]
I'm an idiot and forgot to deploy the plugin changes. Should be good now.
