### ISSUE TITLE
Products - Carousel buttons

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/ukrops_homemades#32]
### Location
Products > Celebration cakes > Testimonials

### Description
The circles and the arrows look squished 

### Screenshot
![carousel](https://cloud.githubusercontent.com/assets/17103891/20767468/57912d4c-b708-11e6-9516-654cb07b2c7a.png)

**Comment by agentdoublel** [comment]
@tfuqua They are either missing now or there's only one testimonial so I cant see them.

**Comment by tfuqua** [comment]
There is only one quote for this page of data. Should be resolved if there is correct data
