### ISSUE TITLE
Homepage - Image overlapping footer

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/ukrops_homemades#33]
### Location
Homepage, last section

### Description
The bottom of the image is overlapping the footer 

### Screenshot
![photo_overlap](https://cloud.githubusercontent.com/assets/17103891/20767542/935ccc3c-b708-11e6-8edf-9970cfb6ef74.png)

**Comment by tfuqua** [comment]
Fixed the height from growing past 100%. I think this should help with issue.

**Comment by agentdoublel** [comment]
Oops. Now it looks like the photo doesnt stretch all the way to to the top (top right)? Is that just the images fault?

<img width="790" alt="screen shot 2016-12-01 at 9 59 59 am" src="https://cloud.githubusercontent.com/assets/17103891/20798488/fa9fcf94-b7ac-11e6-9742-b49ef75f5cc3.png">

**Comment by tfuqua** [comment]
Cropping image fixed the issue
