### ISSUE TITLE
Mobile - Logo isn't centered

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/ukrops_homemades#34]
### Location
globally on Homemades sight

### Description
Logo isn't centered with the screen

### Screenshot
![img_1585](https://cloud.githubusercontent.com/assets/17103891/20769596/af99f390-b710-11e6-954b-54fcb79100f9.PNG)

**Comment by tfuqua** [comment]
fixed margin issue that moved the image too far left. should be centered now.
