### ISSUE TITLE
Feature area padding incorrect

### ISSUE THREAD

**Issue by caitlynmayers** [tfuqua/ukrops_homemades#7]
### Location

http://homemades.taylorfuqua.com/
### Description

The padding around the text in the feature area box is not enough per the comp.
### Screenshot

<img width="537" alt="screen shot 2016-10-19 at 11 13 14 am" src="https://cloud.githubusercontent.com/assets/1574420/19525442/ee0e934e-95ee-11e6-85fb-7b5705fe1acd.png">

**Comment by caitlynmayers** [comment]
@tfuqua This is better, but the top/bottom should have the same padding as left/right.

**Comment by tfuqua** [comment]
@caitlynmayers Will fix. thanks

**Comment by tfuqua** [comment]
Updated to 20px of padding on smaller devices and 34px of padding on larger devices. (looked like in zeplin this was set at 34px;)

**Comment by caitlynmayers** [comment]
Fix verified.
